# Generated by Django 5.1.7 on 2025-03-22 11:57

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('os_project', '0003_migrate_user_data'),
        ('user_profile', '0003_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(default='Select a Country', max_length=2),
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_project.project')),
            ],
        ),
        migrations.CreateModel(
            name='WITFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.payment')),
                ('wit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.womenintech')),
            ],
        ),
    ]
