# Generated by Django 5.1.7 on 2025-03-21 07:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Project categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('repo_link', models.URLField()),
                ('deploy_link', models.URLField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('assigned_wit_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Interest'), ('ASSIGNED', 'WIT Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner Friendly'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=15)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies', max_length=500)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='os_project.projectcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='os_project.projecttag')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('note', models.TextField(blank=True, help_text='Why are you interested in this project?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='os_project.project')),
            ],
            options={
                'unique_together': {('project', 'user_id')},
            },
        ),
    ]
